/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { adminControllerCreateRole } from '../fn/admin/admin-controller-create-role';
import { AdminControllerCreateRole$Params } from '../fn/admin/admin-controller-create-role';
import { adminControllerCreateUser } from '../fn/admin/admin-controller-create-user';
import { AdminControllerCreateUser$Params } from '../fn/admin/admin-controller-create-user';
import { adminControllerDeleteRole } from '../fn/admin/admin-controller-delete-role';
import { AdminControllerDeleteRole$Params } from '../fn/admin/admin-controller-delete-role';
import { adminControllerDeleteUser } from '../fn/admin/admin-controller-delete-user';
import { AdminControllerDeleteUser$Params } from '../fn/admin/admin-controller-delete-user';
import { adminControllerGetAllRoles } from '../fn/admin/admin-controller-get-all-roles';
import { AdminControllerGetAllRoles$Params } from '../fn/admin/admin-controller-get-all-roles';
import { adminControllerGetAllUsers } from '../fn/admin/admin-controller-get-all-users';
import { AdminControllerGetAllUsers$Params } from '../fn/admin/admin-controller-get-all-users';
import { adminControllerUpdateRole } from '../fn/admin/admin-controller-update-role';
import { AdminControllerUpdateRole$Params } from '../fn/admin/admin-controller-update-role';
import { adminControllerUpdateUser } from '../fn/admin/admin-controller-update-user';
import { AdminControllerUpdateUser$Params } from '../fn/admin/admin-controller-update-user';
import { RoleDto } from '../models/role-dto';
import { UserDto } from '../models/user-dto';
import { UserPageResponseDto } from '../models/user-page-response-dto';

@Injectable({ providedIn: 'root' })
export class AdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `adminControllerGetAllUsers()` */
  static readonly AdminControllerGetAllUsersPath = '/api/admin/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminControllerGetAllUsers()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminControllerGetAllUsers$Response(params: AdminControllerGetAllUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<UserPageResponseDto>> {
    return adminControllerGetAllUsers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminControllerGetAllUsers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminControllerGetAllUsers(params: AdminControllerGetAllUsers$Params, context?: HttpContext): Observable<UserPageResponseDto> {
    return this.adminControllerGetAllUsers$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserPageResponseDto>): UserPageResponseDto => r.body)
    );
  }

  /** Path part for operation `adminControllerCreateUser()` */
  static readonly AdminControllerCreateUserPath = '/api/admin/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminControllerCreateUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  adminControllerCreateUser$Response(params: AdminControllerCreateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return adminControllerCreateUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminControllerCreateUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  adminControllerCreateUser(params: AdminControllerCreateUser$Params, context?: HttpContext): Observable<UserDto> {
    return this.adminControllerCreateUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `adminControllerUpdateUser()` */
  static readonly AdminControllerUpdateUserPath = '/api/admin/users/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminControllerUpdateUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  adminControllerUpdateUser$Response(params: AdminControllerUpdateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return adminControllerUpdateUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminControllerUpdateUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  adminControllerUpdateUser(params: AdminControllerUpdateUser$Params, context?: HttpContext): Observable<UserDto> {
    return this.adminControllerUpdateUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `adminControllerDeleteUser()` */
  static readonly AdminControllerDeleteUserPath = '/api/admin/users/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminControllerDeleteUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminControllerDeleteUser$Response(params: AdminControllerDeleteUser$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return adminControllerDeleteUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminControllerDeleteUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminControllerDeleteUser(params: AdminControllerDeleteUser$Params, context?: HttpContext): Observable<boolean> {
    return this.adminControllerDeleteUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `adminControllerGetAllRoles()` */
  static readonly AdminControllerGetAllRolesPath = '/api/admin/roles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminControllerGetAllRoles()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminControllerGetAllRoles$Response(params?: AdminControllerGetAllRoles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleDto>>> {
    return adminControllerGetAllRoles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminControllerGetAllRoles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminControllerGetAllRoles(params?: AdminControllerGetAllRoles$Params, context?: HttpContext): Observable<Array<RoleDto>> {
    return this.adminControllerGetAllRoles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RoleDto>>): Array<RoleDto> => r.body)
    );
  }

  /** Path part for operation `adminControllerCreateRole()` */
  static readonly AdminControllerCreateRolePath = '/api/admin/roles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminControllerCreateRole()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  adminControllerCreateRole$Response(params: AdminControllerCreateRole$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleDto>> {
    return adminControllerCreateRole(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminControllerCreateRole$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  adminControllerCreateRole(params: AdminControllerCreateRole$Params, context?: HttpContext): Observable<RoleDto> {
    return this.adminControllerCreateRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoleDto>): RoleDto => r.body)
    );
  }

  /** Path part for operation `adminControllerUpdateRole()` */
  static readonly AdminControllerUpdateRolePath = '/api/admin/roles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminControllerUpdateRole()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  adminControllerUpdateRole$Response(params: AdminControllerUpdateRole$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return adminControllerUpdateRole(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminControllerUpdateRole$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  adminControllerUpdateRole(params: AdminControllerUpdateRole$Params, context?: HttpContext): Observable<boolean> {
    return this.adminControllerUpdateRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `adminControllerDeleteRole()` */
  static readonly AdminControllerDeleteRolePath = '/api/admin/roles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminControllerDeleteRole()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminControllerDeleteRole$Response(params: AdminControllerDeleteRole$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return adminControllerDeleteRole(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminControllerDeleteRole$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminControllerDeleteRole(params: AdminControllerDeleteRole$Params, context?: HttpContext): Observable<boolean> {
    return this.adminControllerDeleteRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

}
