/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deviceControllerAddNewDevice } from '../fn/device/device-controller-add-new-device';
import { DeviceControllerAddNewDevice$Params } from '../fn/device/device-controller-add-new-device';
import { deviceControllerGetListOfFiles } from '../fn/device/device-controller-get-list-of-files';
import { DeviceControllerGetListOfFiles$Params } from '../fn/device/device-controller-get-list-of-files';
import { deviceControllerGetMyDevices } from '../fn/device/device-controller-get-my-devices';
import { DeviceControllerGetMyDevices$Params } from '../fn/device/device-controller-get-my-devices';
import { deviceControllerRefreshDevice } from '../fn/device/device-controller-refresh-device';
import { DeviceControllerRefreshDevice$Params } from '../fn/device/device-controller-refresh-device';
import { deviceControllerRegisterDevice } from '../fn/device/device-controller-register-device';
import { DeviceControllerRegisterDevice$Params } from '../fn/device/device-controller-register-device';
import { DeviceDto } from '../models/device-dto';
import { FileDto } from '../models/file-dto';

@Injectable({ providedIn: 'root' })
export class DeviceService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `deviceControllerGetMyDevices()` */
  static readonly DeviceControllerGetMyDevicesPath = '/api/device/getMyDevices';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deviceControllerGetMyDevices()` instead.
   *
   * This method doesn't expect any request body.
   */
  deviceControllerGetMyDevices$Response(params?: DeviceControllerGetMyDevices$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DeviceDto>>> {
    return deviceControllerGetMyDevices(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deviceControllerGetMyDevices$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deviceControllerGetMyDevices(params?: DeviceControllerGetMyDevices$Params, context?: HttpContext): Observable<Array<DeviceDto>> {
    return this.deviceControllerGetMyDevices$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DeviceDto>>): Array<DeviceDto> => r.body)
    );
  }

  /** Path part for operation `deviceControllerAddNewDevice()` */
  static readonly DeviceControllerAddNewDevicePath = '/api/device/addNewDevice';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deviceControllerAddNewDevice()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deviceControllerAddNewDevice$Response(params: DeviceControllerAddNewDevice$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return deviceControllerAddNewDevice(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deviceControllerAddNewDevice$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deviceControllerAddNewDevice(params: DeviceControllerAddNewDevice$Params, context?: HttpContext): Observable<string> {
    return this.deviceControllerAddNewDevice$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `deviceControllerRegisterDevice()` */
  static readonly DeviceControllerRegisterDevicePath = '/api/device/registerDevice';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deviceControllerRegisterDevice()` instead.
   *
   * This method doesn't expect any request body.
   */
  deviceControllerRegisterDevice$Response(params?: DeviceControllerRegisterDevice$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deviceControllerRegisterDevice(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deviceControllerRegisterDevice$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deviceControllerRegisterDevice(params?: DeviceControllerRegisterDevice$Params, context?: HttpContext): Observable<void> {
    return this.deviceControllerRegisterDevice$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deviceControllerRefreshDevice()` */
  static readonly DeviceControllerRefreshDevicePath = '/api/device/refreshDevice';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deviceControllerRefreshDevice()` instead.
   *
   * This method doesn't expect any request body.
   */
  deviceControllerRefreshDevice$Response(params?: DeviceControllerRefreshDevice$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deviceControllerRefreshDevice(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deviceControllerRefreshDevice$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deviceControllerRefreshDevice(params?: DeviceControllerRefreshDevice$Params, context?: HttpContext): Observable<void> {
    return this.deviceControllerRefreshDevice$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deviceControllerGetListOfFiles()` */
  static readonly DeviceControllerGetListOfFilesPath = '/api/device/getListOfFiles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deviceControllerGetListOfFiles()` instead.
   *
   * This method doesn't expect any request body.
   */
  deviceControllerGetListOfFiles$Response(params: DeviceControllerGetListOfFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileDto>>> {
    return deviceControllerGetListOfFiles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deviceControllerGetListOfFiles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deviceControllerGetListOfFiles(params: DeviceControllerGetListOfFiles$Params, context?: HttpContext): Observable<Array<FileDto>> {
    return this.deviceControllerGetListOfFiles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FileDto>>): Array<FileDto> => r.body)
    );
  }

}
