/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserWithRolesDto {

  /**
   * Email del usuario
   */
  email: string;

  /**
   * Nombre del usuario
   */
  firstName: string;

  /**
   * Apellido del usuario
   */
  lastName: string;

  /**
   * Roles del usuario
   */
  roles: Array<string>;
}
