/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserDto {

  /**
   * Email del usuario
   */
  email: string;

  /**
   * Nombre del usuario
   */
  firstName: string;

  /**
   * Apellido del usuario
   */
  lastName: string;

  /**
   * Contraseña del usuario
   */
  password: string;
}
