/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeviceDto {

  /**
   * Hostname del dispositivo
   */
  hostname: string;

  /**
   * ID del dispositivo
   */
  id: string;

  /**
   * Nombre del dispositivo
   */
  name: string;

  /**
   * ¿Está el dispositivo en línea?
   */
  online: boolean;

  /**
   * Sistema operativo del dispositivo
   */
  os: string;
}
