/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginUserDto {

  /**
   * Email del usuario
   */
  email: string;

  /**
   * Contraseña del usuario
   */
  password: string;
}
