/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NewRoleDto {

  /**
   * Permisos del rol
   */
  adminRoles: Array<string>;

  /**
   * Permisos del rol
   */
  adminSystem: Array<string>;

  /**
   * Permisos del rol
   */
  adminUsers: Array<string>;

  /**
   * Nombre del rol
   */
  name: string;
}
