/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoleDto {

  /**
   * Permisos del rol
   */
  adminRoles: Array<string>;

  /**
   * Permisos del rol
   */
  adminSystem: Array<string>;

  /**
   * Permisos del rol
   */
  adminUsers: Array<string>;

  /**
   * ID del rol
   */
  id: string;

  /**
   * Nombre del rol
   */
  name: string;
}
