/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserWithRolesDto } from '../models/user-with-roles-dto';
export interface UserPageResponseDto {
  data: Array<UserWithRolesDto>;
  pageNumber: number;
  pageSize: number;
  totalElements: number;
  totalPages: number;
}
