/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {

  /**
   * Permisos efectivos del usuario
   */
  effectivePermissions: {
'adminUsers'?: Array<string>;
'adminSystem'?: Array<string>;
'adminRoles'?: Array<string>;
};

  /**
   * Email del usuario
   */
  email: string;

  /**
   * Nombre del usuario
   */
  firstName: string;

  /**
   * ID del usuario
   */
  id: string;

  /**
   * Apellido del usuario
   */
  lastName: string;
}
