/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserPageResponseDto } from '../../models/user-page-response-dto';

export interface AdminControllerGetAllUsers$Params {
  pageNumber: number;
  pageSize: number;
  order: 'ASC' | 'DESC';
}

export function adminControllerGetAllUsers(http: HttpClient, rootUrl: string, params: AdminControllerGetAllUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<UserPageResponseDto>> {
  const rb = new RequestBuilder(rootUrl, adminControllerGetAllUsers.PATH, 'get');
  if (params) {
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('order', params.order, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserPageResponseDto>;
    })
  );
}

adminControllerGetAllUsers.PATH = '/api/admin/users';
